[workspace]
resolver = "2"
members = [
	# "fuzz",
	"packages/common",
	"packages/staking",
	# "packages/data-requests",
	# "packages/integration-tests",
	# "packages/proxy",
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[workspace.dependencies]
anyhow = "1.0.81"
arbitrary = "1.3"
common = { path = "./packages/common" }
cosmwasm-schema = "1.5"
cosmwasm-std = { version = "1.5" }
cw-multi-test = "1.1"
cw-storage-plus = "1.2"
cw2 = "1.1.2"
cw-utils = "1.0.3"
hex = "0.4.3"
k256 = { version = "0.13", default-features = false, features = [
	"alloc",
	"ecdsa",
] }
libfuzzer-sys = "0.4"
proxy-contract = { path = "./packages/proxy" }
schemars = { version = "0.8", features = ["semver"] }
data-requests = { path = "./packages/data-requests" }
staking = { path = "./packages/staking" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-big-array = { version = "0.5" }
serde_json = "1.0"
sha3 = "0.10"
thiserror = { version = "1.0" }
semver = { version = "1.0", features = ["serde"] }
