[workspace]
resolver = "2"
members = [
    "packages/seda-chain-contracts",
    "packages/wasm-bin-storage",
    "packages/integration-tests",
    "packages/proxy"
]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[workspace.dependencies]
cosmwasm-schema = "1.2"
cosmwasm-std = { version = "1.2", features = ["staking"] }
cosmwasm-storage = "1.1.3"
cw-storage-plus = "1.1"
cw2 = "1.1"
hex = "0.4.3"
proxy-contract = { path = "./packages/proxy" }
schemars = "0.8.10"
seda-chain-contracts = { path = "./packages/seda-chain-contracts" }
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
sha3 = "0.10.8"
thiserror = { version = "1.0.31" }
wasm-bin-storage = { path = "./packages/wasm-bin-storage" }
