[package]
name = "common"
version = "0.1.0"
edition = "2021"

[features]
default = []
testing = []

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-utils = { workspace = true }
k256 = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde-big-array.workspace = true
sha3.workspace = true
thiserror = { workspace = true }
hex = { workspace = true }
semver = { workspace = true }
