[alias]
cov = "run --package xtask -- cov"
cov-ci = "run --package xtask -- cov-ci"
proto-built = "run --package xtask -- build-proto"
proto-update = "run --package xtask -- proto-update"
schema = "run --bin schema"
tally-data-req-fixture = "run --package xtask -- tally-data-req-fixture"
test-all = "run --package xtask -- test-all"
test-ci = "run --package xtask -- test-ci"
test-common = "run --package xtask -- test-common"
test-contract = "run --package xtask -- test-contract"
wasm-opt = "run --package xtask -- wasm-opt"
xtask = "run --package xtask --"

[env]
GIT_REVISION = "unknown"
TEST_CONTRACT_VERSION = "1.0.0"
