[alias]
schema = "run --bin schema"
unit-test = "test --lib"
wasm = "run --package xtask -- wasm"
wasm-opt = "run --package xtask -- wasm-opt"
xtask = "run --package xtask --"
tally-data-req-fixture = "run --package xtask -- tally-data-req-fixture"

[env]
GIT_REVISION = "unknown"
