on:
  workflow_dispatch:

name: Deploy WASM storage to testnet

jobs:
  check_actor:
    runs-on: ubuntu-latest
    outputs:
      is_allowed: ${{ steps.check.outputs.is_allowed }}
    steps:
      - id: check
        run: |
          allowed_users=("FranklinWaller" "gluax" "jamesondh" "mariocao" "mennatbuelnaga" "Thomasvdam")
          for user in "${allowed_users[@]}"
          do
            # The if statement checks who was the actor that triggered the CI seeing if it's an approved user.
            # The triggering_actor is the person who possibly tried to re-run the CI from the actions page.
            # If this exists we check if it's also an approved user.
            if [[ "${{ github.actor }}" == "${user}" && ("${{ github.event.inputs.triggering_actor }}" == "${user}" || "${{ github.event.inputs.triggering_actor }}" == "") ]]; then
              echo "is_allowed=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          done
          echo "is_allowed=false" >> $GITHUB_OUTPUT
  deploys:
    needs: check_actor
    if: ${{ needs.check_actor.outputs.is_allowed == 'true' }}
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.65.0
          target: wasm32-unknown-unknown
          override: true

      - name: Compile optimized WASM contract
        run: |
          docker run --rm -v $GITHUB_WORKSPACE:/code \
          --mount type=volume,source=contract_cache,target=/code/target \
          --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
          cosmwasm/rust-optimizer:0.12.11

      - name: Download seda-chaind binary and make executable
        env:
          SEDACHAIND_FILE_ID: ${{ secrets.SEDACHAIND_FILE_ID }}
        run: |
          sedachaindFileId=${{ env.SEDACHAIND_FILE_ID }}
          sedachaindFileName=seda-chaind-x86-64.tar.gz
          curl -sc /tmp/cookie "https://drive.google.com/uc?export=download&id=${sedachaindFileId}" > /dev/null
          code="$(awk '/_warning_/ {print $NF}' /tmp/cookie)"  
          curl -Lb /tmp/cookie "https://drive.google.com/uc?export=download&confirm=${code}&id=${sedachaindFileId}" -o ${sedachaindFileName} 
          tar -xvf seda-chaind-x86-64.tar.gz
          chmod +x seda-chaind

      - name: Download and decrypt keys
        env:
          KEYRING_PASSWORD: ${{ secrets.KEYRING_PASSWORD }}
          KEYRING_FILE_ID: ${{ secrets.KEYRING_FILE_ID }}
        run: |
          keyringFileId=${{ env.KEYRING_FILE_ID }}
          keyringFileName=keyring.tar.gz.enc
          curl -sc /tmp/cookie "https://drive.google.com/uc?export=download&id=${keyringFileId}" > /dev/null
          code="$(awk '/_warning_/ {print $NF}' /tmp/cookie)"  
          curl -Lb /tmp/cookie "https://drive.google.com/uc?export=download&confirm=${code}&id=${keyringFileId}" -o ${keyringFileName} 
          openssl enc -d -aes-256-cbc -k "$KEYRING_PASSWORD" -salt -pbkdf2 -iter 100000 -in keyring.tar.gz.enc -out keyring.tar.gz
          tar -xvf keyring.tar.gz

      - name: Store contract on chain
        env:
          TESTNET_NODE_URL: ${{ secrets.TESTNET_NODE_URL }}
          DEV_ACCOUNT: ${{ secrets.DEV_ACCOUNT }}
        id: store
        run: |
          testnetNodeUrl=${{ env.TESTNET_NODE_URL }}
          devAccount=${{ env.DEV_ACCOUNT }}
          OUTPUT="$(./seda-chaind tx wasm store ./artifacts/wasm_bin_storage.wasm --node ${testnetNodeUrl} --from ${devAccount} --keyring-dir . --keyring-backend test --gas-prices 0.1aseda --gas auto --gas-adjustment 1.3 -y --output json)"
          TXHASH=$(echo $OUTPUT | jq -r '.txhash')
          echo "Store transaction is $TXHASH"
          echo "txhash=$TXHASH" >> $GITHUB_ENV

      - name: Wait for the transaction to be included in a block
        run: sleep 12

      - name: Find the code ID
        env:
          TESTNET_NODE_URL: ${{ secrets.TESTNET_NODE_URL }}
        id: query
        run: |
          testnetNodeUrl=${{ env.TESTNET_NODE_URL }}
          OUTPUT="$(./seda-chaind query tx ${{ env.txhash }} --node ${testnetNodeUrl} --output json)"
          CODE_ID=$(echo "$OUTPUT" | jq -r '.logs[].events[] | select(.type=="store_code") | .attributes[] | select(.key=="code_id") | .value')
          echo "Code ID is $CODE_ID"
          echo "code_id=$CODE_ID" >> $GITHUB_ENV

      - name: Instantiate contract
        env:
          TESTNET_NODE_URL: ${{ secrets.TESTNET_NODE_URL }}
          DEV_ACCOUNT: ${{ secrets.DEV_ACCOUNT }}
        id: instantiate
        run: |
          testnetNodeUrl=${{ env.TESTNET_NODE_URL }}
          devAccount=${{ env.DEV_ACCOUNT }}
          OUTPUT=$(./seda-chaind tx wasm instantiate ${{ env.code_id }} '{}' --no-admin --from ${devAccount} --node ${testnetNodeUrl} --keyring-dir . --keyring-backend test --label ${{ env.code_id }} --gas-prices 0.1aseda --gas auto --gas-adjustment 1.3 -y --output json)
          TXHASH=$(echo "$OUTPUT" | jq -r '.txhash')
          echo "Instantiate transaction is $TXHASH"
          echo "txhash=$TXHASH" >> $GITHUB_ENV

      - name: Wait for the transaction to be included in a block
        run: sleep 12

      - name: Find the contract address
        env:
          TESTNET_NODE_URL: ${{ secrets.TESTNET_NODE_URL }}
        run: |
          testnetNodeUrl=${{ env.TESTNET_NODE_URL }}
          OUTPUT="$(./seda-chaind query tx ${{ env.txhash }} --node ${testnetNodeUrl} --output json)"
          CONTRACT_ADDRESS=$(echo "$OUTPUT" | jq -r '.logs[].events[] | select(.type=="instantiate") | .attributes[] | select(.key=="_contract_address") | .value')
          echo "Contract address is $CONTRACT_ADDRESS"
