on:
  workflow_dispatch:
    inputs:
      network:
        type: choice
        options:
          - devnet
      contract:
        type: choice
        options:
          - proxy_contract
          - data_requests
          - staking
      password:
        required: true
      proxy:
        required: false

name: Deploy SEDA Contract

jobs:
  check_pass:
    name: Check password
    runs-on: ubuntu-latest
    outputs:
      is_allowed: ${{ steps.check.outputs.is_allowed }}
    steps:
      - id: check
        run: |
          password=${{ secrets.CI_PASSWORD }}
          if [[ "${{ github.event.inputs.password }}" == "${password}" ]]; then
            echo "is_allowed=true" >> $GITHUB_OUTPUT
          else
            echo "is_allowed=false" >> $GITHUB_OUTPUT
          fi

  check_proxy:
    name: Check Proxy
    runs-on: ubuntu-latest
    outputs:
      proxy_ok: ${{ steps.check_proxy.outputs.proxy_ok }}
    steps:
      - id: check_proxy
        run: |
          if [[ "${{ github.event.inputs.contract }}" != "proxy_contract" && -z "${{github.event.inputs.proxy }}" ]]; then
            echo "proxy_ok=false" >> $GITHUB_OUTPUT
          else
            echo "proxy_ok=true" >> $GITHUB_OUTPUT
          fi

  deploys:
    needs: [check_pass, check_proxy]
    if: ${{ needs.check_pass.outputs.is_allowed == 'true' && needs.check_proxy.outputs.proxy_ok == 'true' }}
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Output Contract Name
        run: |
          echo "Contract is ${{ github.event.inputs.contract }}"

      - name: Set Environment Variables
        run: |
          case "${{ github.event.inputs.network }}" in
            devnet)
              echo "Setting NODE_URL for devnet"
              echo "NODE_URL=${{ secrets.TESTNET_NODE_URL }}" >> $GITHUB_ENV
              ;;
          esac

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.72.1
          target: wasm32-unknown-unknown

      - name: Compile optimized WASM contract
        run: |
          docker run --rm -v $GITHUB_WORKSPACE:/code \
          --mount type=volume,source=contract_cache,target=/code/target \
          --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
          cosmwasm/rust-optimizer:0.12.11

      - name: Download seda-chaind binary and make executable
        env:
          SEDACHAIND_FILE_ID: ${{ secrets.SEDACHAIND_FILE_ID }}
        run: |
          sedachaindFileId=${{ env.SEDACHAIND_FILE_ID }}
          sedachaindFileName=seda-chaind-x86-64.tar.gz
          curl -sc /tmp/cookie "https://drive.google.com/uc?export=download&id=${sedachaindFileId}" > /dev/null
          code="$(awk '/_warning_/ {print $NF}' /tmp/cookie)"
          curl -Lb /tmp/cookie "https://drive.google.com/uc?export=download&confirm=${code}&id=${sedachaindFileId}" -o ${sedachaindFileName}
          tar -xvf seda-chaind-x86-64.tar.gz
          chmod +x seda-chaind

      - name: Download and decrypt keys
        env:
          KEYRING_PASSWORD: ${{ secrets.KEYRING_PASSWORD }}
          KEYRING_FILE_ID: ${{ secrets.KEYRING_FILE_ID }}
        run: |
          keyringFileId=${{ env.KEYRING_FILE_ID }}
          keyringFileName=keyring.tar.gz.enc
          curl -sc /tmp/cookie "https://drive.google.com/uc?export=download&id=${keyringFileId}" > /dev/null
          code="$(awk '/_warning_/ {print $NF}' /tmp/cookie)"
          curl -Lb /tmp/cookie "https://drive.google.com/uc?export=download&confirm=${code}&id=${keyringFileId}" -o ${keyringFileName}
          openssl enc -d -aes-256-cbc -k "$KEYRING_PASSWORD" -salt -pbkdf2 -iter 100000 -in keyring.tar.gz.enc -out keyring.tar.gz
          tar -xvf keyring.tar.gz

      - name: Store contract on chain
        env:
          DEV_ACCOUNT: ${{ secrets.DEV_ACCOUNT }}
        id: store
        run: |
          nodeUrl=${{ env.NODE_URL }}
          devAccount=${{ env.DEV_ACCOUNT }}
          OUTPUT="$(./seda-chaind tx wasm store ./artifacts/${{ github.event.inputs.contract }}.wasm --node ${nodeUrl} --from ${devAccount} --keyring-dir . --keyring-backend test --gas-prices 0.1aseda --gas auto --gas-adjustment 1.3 -y --output json)"
          TXHASH=$(echo $OUTPUT | jq -r '.txhash')
          echo "Store transaction is $TXHASH"
          echo "txhash=$TXHASH" >> $GITHUB_ENV

      - name: Wait for the transaction to be included in a block
        run: sleep 12

      - name: Find the code ID
        id: query
        run: |
          nodeUrl=${{ env.NODE_URL }}
          OUTPUT="$(./seda-chaind query tx ${{ env.txhash }} --node ${nodeUrl} --output json)"
          CODE_ID=$(echo "$OUTPUT" | jq -r '.logs[].events[] | select(.type=="store_code") | .attributes[] | select(.key=="code_id") | .value')
          echo "Code ID is $CODE_ID"
          echo "code_id=$CODE_ID" >> $GITHUB_ENV

      - name: Instantiate contract
        env:
          DEV_ACCOUNT: ${{ secrets.DEV_ACCOUNT }}
        id: instantiate
        run: |
          nodeUrl=${{ env.NODE_URL }}
          devAccount=${{ env.DEV_ACCOUNT }}
          if [[ "${{ github.event.inputs.contract }}" != "proxy_contract" ]]; then
            proxy=${{ github.event.inputs.proxy }}
            OUTPUT=$(./seda-chaind tx wasm instantiate ${{ env.code_id }} '{"token":"aseda", "proxy": ${{ toJSON(github.event.inputs.proxy) }} }' --no-admin --from ${devAccount} --node ${nodeUrl} --keyring-dir . --keyring-backend test --label ${{ env.code_id }} --gas-prices 0.1aseda --gas auto --gas-adjustment 1.3 -y --output json)
          else
            OUTPUT=$(./seda-chaind tx wasm instantiate ${{ env.code_id }} '{"token":"aseda"}' --no-admin --from ${devAccount} --node ${nodeUrl} --keyring-dir . --keyring-backend test --label ${{ env.code_id }} --gas-prices 0.1aseda --gas auto --gas-adjustment 1.3 -y --output json)
          fi
          TXHASH=$(echo "$OUTPUT" | jq -r '.txhash')
          echo "Instantiate transaction is $TXHASH"
          echo "txhash=$TXHASH" >> $GITHUB_ENV

      - name: Wait for the transaction to be included in a block
        run: sleep 12

      - name: Find the contract address
        run: |
          nodeUrl=${{ env.NODE_URL }}
          OUTPUT="$(./seda-chaind query tx ${{ env.txhash }} --node ${nodeUrl} --output json)"
          CONTRACT_ADDRESS=$(echo "$OUTPUT" | jq -r '.logs[].events[] | select(.type=="instantiate") | .attributes[] | select(.key=="_contract_address") | .value')
          echo "Contract address is $CONTRACT_ADDRESS"
